### ISSUE TITLE
Getting issue

### ISSUE THREAD

**Issue by doxmeifucan** [abdlalisalmi/wistia-downloader#1]
![image](https://user-images.githubusercontent.com/43927831/79067301-2e540c00-7ce0-11ea-895b-702ee9cd5fd3.png)

Getting this issue.

Any possible fix?

**Comment by abdlalisalmi** [comment]
if you run it on Windows, just change "/" with "\\"

**Comment by doxmeifucan** [comment]
> if you run it on Windows, just change "/" with "\"

I am using on Google Colab

**Comment by Adarsh777** [comment]
> if you run it on Windows, just change "/" with "\"

I'm running on windows but getting the same error as @aaahimel and also tried changing 
`"/ " with " \ "` but not working.

**Comment by SandeepBalachandran** [comment]
Getting the same error on windows

**Comment by abdlalisalmi** [comment]
When I created the script I used it on Linux, and I didn't consider Windows.
It did not work with you on Windows because the system architecture is
different from Linux, I will soon make a copy for Windows.

**Comment by Adarsh777** [comment]
> When I created the script I used it on Linux, and I didn't consider Windows. It did not work with you on Windows because the system architecture is different from Linux, I will soon make a copy for Windows.

Okay will wait for the windows version 😊

**Comment by doxmeifucan** [comment]
> When I created the script I used it on Linux, and I didn't consider Windows. It did not work with you on Windows because the system architecture is different from Linux, I will soon make a copy for Windows.

Waiting for it

**Comment by abdlalisalmi** [comment]
The script is working fine now on Windows, I wish you like it.
@aaahimel @Adarsh777 @SandeepBalachandran
