### ISSUE TITLE
Set desired resolution size

### ISSUE THREAD

**Issue by pin147** [abdlalisalmi/wistia-downloader#3]
Hi,

Awesome script! Do you think you have the time to add the option to set a desired resolution for the downloaded video? The source videos are way too big. There's this repo: https://github.com/mccannjb/Wistia-video-fetcher that has the option to set the resolution but there is no progress when downloading. And it's really helpful. I'd do it myself but my programming skills are so bad that I can't really understand how it all works.

Cheers

**Comment by abdlalisalmi** [comment]
hello @pin147 , 
I will add this feature very soon and thank you for the suggestion.

**Comment by pin147** [comment]
Wow, awesome. There's also a little annoying issue with the filename. It's quite tedious to go and rename all the downloaded files. In the future, if you can also add the option to have a custom file name when adding the IDs would be great. That script also does that and it's easy to just batch download and have them with the name and in the order that you want.

**Comment by abdlalisalmi** [comment]
@pin147 , The quality selection feature has been added you can check it, as for the ability to change the name, we will work on it as soon.
